### ISSUE TITLE
rescom17

### ISSUE THREAD

**Issue by Tugdwal** [BeyondTheClouds/enos-scenarios#2]
2.3.1 Unleash the Operator in You

[...]

With the previous `openstack sever create` command, the VM boot with a private IP. Private IPs are used for communication between VMs, meaning you cannot ping your VM from the lab machine. Network lovers will find a challenge here: try to ping the VM from the lab machine. For the others, you have to manually affect a floating IP to your machine if you want it pingable from the lab.

=> `openstack server create`

**Comment by rcherrueau** [comment]
Fix in 870aa2b 

👍
